# https://hub.docker.com/_/microsoft-dotnet-core
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /source

# copy csproj and restore as distinct layers
COPY . .
RUN dotnet restore GalaxyWebApi.sln

# copy everything else and build app
COPY . .
RUN dotnet publish -c release -o /app --no-restore GalaxyWebApi.sln

# final stage/image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "GalaxyWebApi.dll"]