# https://hub.docker.com/_/microsoft-dotnet-core
FROM mcr.microsoft.com/dotnet/core/sdk:3.1
COPY GalaxyWebApi/build ./
WORKDIR ./
EXPOSE 80 5001
EXPOSE 443 5000
ENTRYPOINT ["dotnet", "GalaxyWebApi.dll"]