name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  PROJECT_NAME: GalaxyWebApi

jobs:
  build:
    env:
      SOLUTION_PATH: ./${env.PROJECT_NAME}/${env.PROJECT_NAME}.sln
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore "${env.SOLUTION_PATH}"
    - name: Build
      run: dotnet build --configuration Release --no-restore "${env.SOLUTION_PATH}"
    # интеграционное тестирвоание будет здесь падать. Нужно подготовить БД(не локальную), в которой можно будет выполнять тестирование
    #- name: Test
    #  run: dotnet test --no-restore --verbosity normal "${env.SOLUTION_PATH}"
    - name: Azure WebApp
      uses: Azure/webapps-deploy@v2
      with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }} # Replace with your app name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }} # Define secret variable in repository settings as per action documentation
          #package: '${{ secrets.AZURE_WEBAPP_PACKAGE_PATH }}/myapp'
