name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  PROJECT_NAME: GalaxyWebApi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
        
    - name: Login via Az module
      uses: azure/login@v1.1
      with:
        creds: ${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
        enable-AzPSSession: true 
        
      #Build
    - name: Install dependencies
      run: dotnet restore "./${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.sln"
    - name: Build
      run: dotnet publish -c release -o ${{ env.PROJECT_NAME }}/build --no-restore "./${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.sln"
      
      # image
    - name: Image
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ secrets.DOCKER_REPO }}
        tags: latest
        dockerfile: ./${{env.PROJECT_NAME}}/dockerfile
    # интеграционное тестирвоание будет здесь падать. Нужно подготовить БД(не локальную), в которой можно будет выполнять тестирование
    #- name: Test
    #  run: dotnet test --no-restore --verbosity normal "${{env.SOLUTION_PATH}}"
      
    - name: Deploy
      uses: Azure/webapps-deploy@v2
      with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }} 
          images: '${{ secrets.DOCKER_REPO }}:latest'
