name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore "./GalaxyWebApi/GalaxyWebApi.sln"
    - name: Build
      run: dotnet build --configuration Release --no-restore "./GalaxyWebApi/GalaxyWebApi.sln"
    # интеграционное тестирвоание будет здесь падать. Нужно подготовить БД(не локальную), в которой можно будет выполнять тестирование
    #- name: Test
    #  run: dotnet test --no-restore --verbosity normal "./GalaxyWebApi/GalaxyWebApi.sln"
